# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: "Build"

on:
  push:
    branches: ['main']
    paths:
    - 'plugin/**'
#    - '.github/**'

jobs:
  build-and-push-image:
    if: ${{ !contains(github.event.head_commit.message, '#skip-actions') }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    defaults:
      run:
        working-directory: plugin
    environment: production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint
        run: |
          pylint $(git ls-files '*.py') --fail-under=10

      - name: Get version
        id: metadata
        run: |
            version=$(cat .version)
            echo "version=${version}" >> $GITHUB_OUTPUT

      - name: Package
        run: |
          pyinstaller -F --path venv/lib64/python3.10/site-packages kubectl-swissknife.py
        
      - name: Check
        run: |
            ll
            ll dist